import { invoke } from "@tauri-apps/api/core";
import { listen } from "@tauri-apps/api/event";
import { open } from "@tauri-apps/plugin-dialog";
import "./chat.css";

type Message={runs?:{text:string;image?:string}[];id:string;time:number;author:string;authorId:string;text:string;kind:string;amount?:string};
type Peak={start:number;end:number;count:number};
type Edit={name:string;fps:number;duration:number;cuts:{sourceIn:number;sourceOut:number;start:number;end:number}[]};
type Report={title:string;duration:number;messages:Message[];normal:number;superChat:number;superSticker:number;memberships:number;participants:number;untimed:number;malformed:number;peaks:Peak[];activity:Peak[];rawPath:string;edit?:Edit};
type Options={width:number;height:number;fontSize:number;historyFontSize:number;historyOpacity:number;maxMessages:number;lifetime:number;carrySeconds:number;carryCount:number;offset:number;fps:number};
type Timed={message:Message;start:number;end:number;past:boolean};
type Status={jobId:string;stage:string;message:string;percent?:number};
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
const messageHtml=(m:Message)=>m.runs?.length?m.runs.map(r=>r.image?`<img class="chat-emote" src="${escape(r.image)}" alt="${escape(r.text||"emote")}" title="${escape(r.text||"emote")}" referrerpolicy="no-referrer">`:escape(r.text)).join(""):escape(m.text);
const time=(s:number)=>{s=Math.max(0,Math.floor(s));return`${String(Math.floor(s/3600)).padStart(2,"0")}:${String(Math.floor(s/60)%60).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`};

export async function initChat(app:HTMLElement){
  const query=new URLSearchParams(location.search),jobId=query.get("chat")!,tr=query.get("lang")!=="en";
  const l=(a:string,b:string)=>tr?a:b;
  let report:Report|undefined,filtered:Message[]=[],mapped:Timed[]=[],rawPage=0,mode="messages",busy=false,previewTime=0,timingRequest=0,lastExportPath="";
  const defaults:Options={width:480,height:900,fontSize:24,historyFontSize:20,historyOpacity:0.65,maxMessages:5,lifetime:12,carrySeconds:8,carryCount:5,offset:0,fps:30};
  let options={...defaults};try{options={...defaults,...JSON.parse(localStorage.getItem(`chat-widget-${jobId}`)||"{}")}}catch{}
  document.body.classList.add("chat-page");
  app.innerHTML=`<header class="chat-header"><div><span class="chat-eyebrow">YOUTUBE LIVE DOWNLOADER / CHAT STUDIO</span><h1 id="chat-title">${l("Sohbet arşivi","Chat archive")}</h1></div><div class="chat-header-buttons"><button id="chat-folder">${l("Klasörde Göster","Show in Folder")}</button><button id="chat-download" class="primary">${l("Sohbeti İndir","Download Chat")}</button></div></header>
  <div class="chat-status" role="status"><span id="chat-status">${l("Sohbet kaydı kontrol ediliyor…","Checking chat archive…")}</span><progress id="chat-progress" max="100" hidden></progress><button id="chat-cancel" hidden>${l("İptal","Cancel")}</button></div>
  <nav class="chat-tabs"><button class="selected" data-tab="archive">${l("Arşiv ve yoğun anlar","Archive & highlights")}</button><button data-tab="widget">${l("Resolve ve sohbet katmanı","Resolve & chat overlay")}</button></nav>
  <main class="chat-layout" id="archive-tab"><aside class="chat-sidebar"><h2>${l("Yayına genel bakış","Stream overview")}</h2><div class="chat-stats" id="chat-stats"></div><p id="chat-warnings" class="chat-muted"></p><div id="chat-chart"></div><h2>${l("En yoğun 15 saniye","Busiest 15 seconds")}</h2><p class="chat-muted">${l("1 saniye adım • çakışan zirveler gruplanır","1-second step • overlapping peaks grouped")}</p><div id="chat-peaks" class="chat-peak-list"></div><h2>Super Chat / Super Sticker</h2><div id="chat-paid" class="chat-peak-list"></div></aside>
  <section class="chat-stream-panel"><div class="chat-stream-toolbar"><input id="chat-search" placeholder="${l("Kullanıcı veya mesaj ara…","Search author or message…")}"><select id="chat-kind"><option value="all">${l("Tüm mesajlar","All messages")}</option><option value="normal">${l("Normal","Normal")}</option><option value="superchat">Super Chat</option><option value="supersticker">Super Sticker</option><option value="membership">${l("Üyelik","Membership")}</option></select><button id="chat-raw">${l("Ham JSON","Raw JSON")}</button></div><p id="chat-count" class="chat-muted"></p><div id="chat-stream" tabindex="0"><div id="chat-spacer"></div><div id="chat-rows"></div></div><section id="raw-panel" hidden><div class="raw-controls"><button id="raw-prev">←</button><span id="raw-page"></span><button id="raw-next">→</button></div><pre id="raw-text"></pre></section><div id="chat-detail" class="chat-detail">${l("Mesaj zamanına tıklayarak videoda o ana gidebilirsin. Mesaj metnine tıkla: tamamını göster.","Click a timestamp to seek in the video. Click a message to read its full text.")}</div></section></main>
  <main class="widget-layout" id="widget-tab" hidden><section class="widget-settings"><h2>1. ${l("Resolve kesimleri","Resolve edit")}</h2><p>${l("Resolve: File → Export → Timeline → Final Cut Pro 7 XML. Tek etkin video kanalı, normal hız ve düz kesimler kullanın.","Resolve: File → Export → Timeline → Final Cut Pro 7 XML. Use one enabled video track, normal speed and straight cuts.")}</p><button id="import-xml">${l("Resolve XML İçe Aktar","Import Resolve XML")}</button><p id="edit-summary" class="chat-muted"></p><label class="use-edit"><input id="use-edit" type="checkbox"> ${l("Resolve kesimlerini uygula","Apply Resolve edit")}</label>
  <h2>2. ${l("Widget görünümü ve süreler","Widget appearance & timing")}</h2><div class="widget-fields">${field("width",l("Genişlik (px)","Width (px)"),240,1920)}${field("height",l("Yükseklik (px)","Height (px)"),240,2160)}${field("fontSize",l("Yazı boyutu","Font size"),12,64)}${field("maxMessages",l("Görünen mesaj","Visible messages"),1,12)}${field("lifetime",l("Mesaj süresi (sn)","Message lifetime (s)"),1,120)}${field("carryCount",l("Geçmiş mesaj adedi","Carried messages"),0,12)}${field("carrySeconds",l("Geçmiş mesaj süresi (sn)","History lifetime (s)"),0,60)}${field("historyFontSize",l("Geçmiş mesaj yazı boyutu","History font size"),12,64)}${field("historyOpacity",l("Geçmiş mesaj opaklığı (0–1)","History opacity (0–1)"),0,1,.05)}${field("offset",l("Sohbet zaman kaydırma (sn)","Chat offset (s)"),-86400,86400,.1)}${field("fps",l("Çıktı FPS (orijinal)","Output FPS (original)"),1,60,.001)}</div>
  <p class="chat-muted">${l("Geçmiş mesajların yazı boyutu ve opaklığı ayrı ayarlanır. Süreler üst sınırdır: mesaj adedi veya dikey alan dolunca eski mesajlar daha erken üstten çıkar. Kesim geçişleri süreyi sıfırlamaz. YouTube emote görselleri gösterilir; MOV çıktısında da yer alır.","History has separate font size and opacity. Lifetimes are upper limits: message count or vertical space can push older messages out sooner. Cuts do not reset lifetimes. YouTube emote images appear in the preview and MOV export.")}</p>
  <h2>3. ${l("Dışa aktar","Export")}</h2><div class="chat-export-buttons"><button id="preview-mov">${l("15 sn MOV Örneği","15s MOV Sample")}</button><button id="export-mov" class="primary">${l("Şeffaf MOV Oluştur","Render Alpha MOV")}</button><select id="srt-kind"><option value="all">SRT · ${l("Tüm mesajlar","All messages")}</option><option value="paid">SRT · Super Chat / Sticker</option><option value="peaks">SRT · ${l("Yoğun anlar","Highlights")}</option></select><button id="export-srt">${l("SRT Kaydet","Save SRT")}</button></div><p class="chat-muted">${l("MOV: QuickTime Animation + alfa. Resolve’da üst video kanalına, timeline başlangıcına yerleştirin. Uzun yayınlarda çıktı büyük olabilir; önce 15 saniyelik örneği deneyin. SRT görsel widget içermez.","MOV: QuickTime Animation with alpha. Place on an upper video track at the start of your Resolve timeline. Long streams can create large files; try the 15-second sample first. SRT does not include widget styling.")}</p><p id="export-timeline" class="chat-muted"></p><p id="export-result" class="chat-output"></p><button id="export-folder" hidden>${l("Çıktı Klasörünü Aç","Open Export Folder")}</button></section>
  <section class="widget-preview-panel"><div class="widget-preview-heading"><h2>${l("Sohbet önizlemesi","Chat preview")}</h2><output id="preview-clock">00:00:00</output></div><div id="widget-preview"><div id="widget-canvas"></div></div><input id="preview-seek" type="range" min="0" max="1" step="0.1" value="0"><div class="preview-actions"><button id="preview-first">${l("İlk mesaja git","First message")}</button><button id="preview-source">${l("Orijinal videoda aç","Open in source video")}</button></div><p class="chat-muted">${l("Damalı alan şeffaflığı gösterir. MOV örneği gerçek dışa aktarım görünümünü doğrulamanızı sağlar.","Checkerboard indicates transparency. The MOV sample shows the actual rendered appearance.")}</p></section></main>`;
  function field(key:keyof Options,title:string,min:number,max:number,step=1){return`<label>${title}<input data-option="${key}" type="number" value="${options[key]}" min="${min}" max="${max}" step="${step}"></label>`}
  const $=<T extends HTMLElement=HTMLElement>(selector:string)=>app.querySelector<T>(selector)!;
  const note=(message:string)=>$("#chat-status").textContent=message;
  const fail=(e:unknown)=>note(String(e));
  function setBusy(value:boolean){busy=value;$("#chat-cancel").hidden=!value;$("#chat-progress").hidden=!value;for(const id of ["chat-download","import-xml","preview-mov","export-mov","export-srt"])( $<HTMLButtonElement>(`#${id}`)).disabled=value}
  function useEdit(){return $<HTMLInputElement>("#use-edit").checked}
  function readOptions(){for(const input of app.querySelectorAll<HTMLInputElement>("[data-option]")){if(!input.checkValidity())throw new Error(l("Widget ayarlarını kontrol edin.","Check widget settings."));options[input.dataset.option as keyof Options]=Number(input.value)}localStorage.setItem(`chat-widget-${jobId}`,JSON.stringify(options));return options}
  const play=(seconds:number)=>invoke("open_player",{jobId,seconds}).catch(fail);
  async function accept(data:Report){report=data;$("#chat-title").textContent=data.title;$("#chat-download").textContent=l("Arşiv Hazır","Archive Ready");const stats=[[l("Toplam","Total"),data.messages.length],[l("Katılımcı","Participants"),data.participants],[l("Normal","Normal"),data.normal],["Super Chat",data.superChat],["Super Sticker",data.superSticker],[l("Üyelik","Membership"),data.memberships]];$("#chat-stats").innerHTML=stats.map(([label,n])=>`<div><strong>${Number(n).toLocaleString()}</strong><span>${label}</span></div>`).join("");$("#chat-warnings").textContent=l(`Zamanı olmayan/başlangıç öncesi: ${data.untimed} · Okunamayan JSON satırı: ${data.malformed}. İstatistikler indirilebilen mesajları kapsar.`,`Untimed/pre-start: ${data.untimed} · Invalid JSON lines: ${data.malformed}. Statistics cover available messages.`);
    $("#chat-peaks").innerHTML=data.peaks.map(p=>`<button data-time="${p.start}"><span>${time(p.start)}–${time(p.end)}</span><strong>${p.count}</strong></button>`).join("")||l("Mesaj bulunamadı.","No messages found.");
    const paid=data.messages.filter(m=>m.kind==="superchat"||m.kind==="supersticker");$("#chat-paid").innerHTML=paid.map(m=>`<button data-time="${m.time}"><span>${time(m.time)} · ${escape(m.author)}</span><strong>${escape(m.amount||m.kind)}</strong></button>`).join("")||l("Ücretli mesaj yok.","No paid messages.");
    app.querySelectorAll<HTMLElement>("[data-time]").forEach(b=>b.onclick=()=>jump(Number(b.dataset.time)));
    const max=data.activity.reduce((n,p)=>Math.max(n,p.count),1);$("#chat-chart").innerHTML=`<svg viewBox="0 0 300 72" aria-label="Chat activity"><polyline fill="none" stroke="#77d9a1" stroke-width="2" points="${data.activity.map(p=>`${p.start/Math.max(1,data.duration)*300},${68-p.count/max*60}`).join(" ")}"/></svg>`;
    $("#edit-summary").textContent=data.edit?`${data.edit.name} · ${data.edit.cuts.length} ${l("kesim","cuts")} · ${time(data.edit.duration)} · ${data.edit.fps.toFixed(3)} FPS`:l("XML yüklenmedi; orijinal zaman çizelgesi kullanılacak.","No XML imported; original timeline is used.");
    $<HTMLInputElement>("#use-edit").disabled=!data.edit;
    $<HTMLInputElement>("#use-edit").checked=!!data.edit&&localStorage.getItem(`chat-use-edit-${jobId}`)!=="false";
    filter();await refreshTiming();
  }
  function filter(){const search=$<HTMLInputElement>("#chat-search").value.toLocaleLowerCase(),kind=$<HTMLSelectElement>("#chat-kind").value;filtered=(report?.messages||[]).filter(m=>(kind==="all"||m.kind===kind)&&`${m.author} ${m.text} ${m.amount||""}`.toLocaleLowerCase().includes(search));$("#chat-count").textContent=`${filtered.length.toLocaleString()} ${l("mesaj · orijinal video zamanı","messages · original video time")}`;$("#chat-stream").scrollTop=0;drawRows()}
  function drawRows(){const host=$("#chat-stream"),rowHeight=96,start=Math.max(0,Math.floor(host.scrollTop/rowHeight)-3),end=Math.min(filtered.length,start+Math.ceil(host.clientHeight/rowHeight)+7);$("#chat-spacer").style.height=`${filtered.length*rowHeight}px`;const rows=$("#chat-rows");rows.style.transform=`translateY(${start*rowHeight}px)`;rows.innerHTML=filtered.slice(start,end).map((m,i)=>`<article class="chat-message ${m.kind}" data-index="${start+i}"><button class="message-time">${time(m.time)}</button><div><b>${escape(m.author)} ${m.amount?`<em>${escape(m.amount)}</em>`:""}</b><p>${messageHtml(m)}</p></div></article>`).join("");rows.querySelectorAll<HTMLElement>(".chat-message").forEach(row=>{const m=filtered[Number(row.dataset.index)];row.querySelector<HTMLButtonElement>("button")!.onclick=()=>play(m.time);row.querySelector<HTMLElement>("div")!.onclick=()=>{$("#chat-detail").textContent=`${time(m.time)} · ${m.author} ${m.amount||""}\n${m.text}`}})}
  function jump(seconds:number){$<HTMLInputElement>("#chat-search").value="";$<HTMLSelectElement>("#chat-kind").value="all";filter();const i=filtered.findIndex(m=>m.time>=seconds);$("#chat-stream").scrollTop=Math.max(0,i)*96;drawRows();previewTime=seconds;drawPreview()}
  async function refreshTiming(){if(!report)return;$("#export-timeline").textContent=useEdit()?l("MOV ve SRT: XML kesimlerine göre yeni zaman çizelgesi kullanılıyor.","MOV and SRT: edited XML timeline is active."):l("MOV ve SRT: orijinal video zamanları kullanılıyor.","MOV and SRT: original video timestamps are active.");const request=++timingRequest;try{const items=await invoke<Timed[]>("get_chat_timing",{jobId,options:readOptions(),useEdit:useEdit()});if(request!==timingRequest)return;mapped=items;$<HTMLInputElement>("#preview-seek").max=String(useEdit()?report.edit!.duration:report.duration);drawPreview()}catch(e){fail(e)}}
  function authorColor(author:string){let n=0;for(const b of new TextEncoder().encode(author))n=(Math.imul(n,31)+b)>>>0;return ["#72df9b","#7bc1f2","#cb9fe4","#f2dc74"][n%4]}
  function drawPreview(){const canvas=$("#widget-canvas"),preview=$("#widget-preview");canvas.style.width=`${options.width}px`;canvas.style.height=`${options.height}px`;canvas.style.fontSize=`${options.fontSize}px`;const scale=Math.min(preview.clientWidth/options.width,preview.clientHeight/options.height);canvas.style.transform=`scale(${scale})`;let visible:Timed[]=[];for(const m of mapped){if(m.start>previewTime)break;visible=visible.filter(old=>old.end>m.start);visible.push(m);visible=visible.slice(-options.maxMessages)}visible=visible.filter(m=>m.end>previewTime);canvas.innerHTML=visible.map(m=>`<div class="widget-message ${m.message.kind}" style="font-size:${m.past?options.historyFontSize:options.fontSize}px;opacity:${m.past?options.historyOpacity:1}"><b style="color:${m.message.kind==='normal'?authorColor(m.message.author):'#ffd95b'}">${escape(m.message.author)} ${escape(m.message.amount||"")}</b><span> ${messageHtml(m.message)}</span></div>`).join("");$("#preview-clock").textContent=time(previewTime);$<HTMLInputElement>("#preview-seek").value=String(previewTime)}
  async function raw(){try{const text=await invoke<string>("chat_raw_page",{jobId,page:rawPage});$("#raw-text").textContent=text||l("Dosya sonu","End of file");$("#raw-page").textContent=`${rawPage*20+1}–${rawPage*20+20}`;$<HTMLButtonElement>("#raw-prev").disabled=rawPage===0;$<HTMLButtonElement>("#raw-next").disabled=!text}catch(e){fail(e)}}
  async function exportFile(command:string,extra:Record<string,unknown>){try{setBusy(true);const path=await invoke<string>(command,{jobId,options:readOptions(),useEdit:useEdit(),...extra});lastExportPath=path;$("#export-result").textContent=path;$("#export-folder").hidden=false;note(l("Çıktı hazır; Klasörde Göster ile açabilirsiniz.","Export ready; use Show in Folder to find it."))}catch(e){fail(e)}finally{setBusy(false)}}
  $("#export-folder").onclick=()=>invoke("open_chat_export_folder",{jobId,path:lastExportPath}).catch(fail);
  $("#chat-folder").onclick=()=>invoke("open_job_folder",{jobId}).catch(fail);
  $("#chat-download").onclick=async()=>{try{setBusy(true);await accept(await invoke<Report>("download_chat",{jobId}));note(l("Sohbet hazır. Ham dosya korunuyor.","Chat ready. Raw file preserved."))}catch(e){fail(e)}finally{setBusy(false)}};
  $("#chat-cancel").onclick=()=>invoke("cancel_chat",{jobId}).catch(fail);
  $("#chat-search").oninput=filter;$("#chat-kind").onchange=filter;$("#chat-stream").onscroll=drawRows;
  $("#chat-raw").onclick=()=>{mode=mode==="messages"?"raw":"messages";$("#raw-panel").hidden=mode!=="raw";$("#chat-stream").hidden=mode!=="messages";$("#chat-raw").textContent=mode==="raw"?l("Mesajlar","Messages"):l("Ham JSON","Raw JSON");if(mode==="raw")void raw();else drawRows()};
  $("#raw-prev").onclick=()=>{rawPage=Math.max(0,rawPage-1);void raw()};$("#raw-next").onclick=()=>{rawPage++;void raw()};
  app.querySelectorAll<HTMLElement>("[data-tab]").forEach(button=>button.onclick=()=>{app.querySelectorAll("[data-tab]").forEach(b=>b.classList.toggle("selected",b===button));$("#archive-tab").hidden=button.dataset.tab!=="archive";$("#widget-tab").hidden=button.dataset.tab!=="widget";drawRows();drawPreview()});
  $("#import-xml").onclick=async()=>{try{const path=await open({multiple:false,filters:[{name:"Final Cut Pro 7 XML",extensions:["xml"]}]});if(typeof path!=="string")return;await invoke("import_resolve_xml",{jobId,path});localStorage.setItem(`chat-use-edit-${jobId}`,"true");$<HTMLInputElement>("#use-edit").checked=true;await accept(await invoke<Report>("get_chat",{jobId}));note(l("Kesimler içe aktarıldı.","Edit imported."))}catch(e){fail(e)}};
  $("#use-edit").onchange=()=>{localStorage.setItem(`chat-use-edit-${jobId}`,String(useEdit()));void refreshTiming()};app.querySelectorAll<HTMLInputElement>("[data-option]").forEach(input=>input.onchange=()=>void refreshTiming());
  $("#preview-seek").oninput=e=>{previewTime=Number((e.target as HTMLInputElement).value);drawPreview()};
  $("#preview-first").onclick=()=>{previewTime=mapped[0]?.start||0;drawPreview()};
  $("#preview-source").onclick=()=>{const cut=useEdit()?report?.edit?.cuts.find(c=>c.start<=previewTime&&c.end>previewTime):undefined;void play(cut?cut.sourceIn+previewTime-cut.start:previewTime)};
  $("#preview-mov").onclick=()=>void exportFile("render_chat_overlay",{preview:true});$("#export-mov").onclick=()=>void exportFile("render_chat_overlay",{preview:false});$("#export-srt").onclick=()=>void exportFile("export_chat_text",{kind:$<HTMLSelectElement>("#srt-kind").value});
  window.addEventListener("resize",()=>{drawRows();drawPreview()});
  await listen<Status>("chat-progress",e=>{if(e.payload.jobId!==jobId)return;const s=e.payload;note(s.message);$<HTMLProgressElement>("#chat-progress").value=s.percent||0;setBusy(s.stage==="downloading"||s.stage==="rendering");if(s.stage==="ready")void invoke<Report>("get_chat",{jobId}).then(accept).catch(fail)});
  let saved:Status|undefined;try{saved=await invoke<Status|undefined>("get_chat_status",{jobId});if(saved){note(saved.message);setBusy(["downloading","rendering"].includes(saved.stage))}await accept(await invoke<Report>("get_chat",{jobId}));if(!busy)note(l("Sohbet arşivi hazır.","Chat archive ready."))}catch{if(!busy)note(saved?.message||l("Henüz sohbet arşivi yok. ‘Sohbeti İndir’ ile bu videonun sohbet tekrarını alabilirsiniz.","No chat archive yet. Use Download Chat to retrieve this video's replay."))}
}
