import { invoke } from "@tauri-apps/api/core";
import { listen } from "@tauri-apps/api/event";
import { open } from "@tauri-apps/plugin-dialog";
import "./styles.css";
import "./resilience.css";

type Language="en"|"tr";
type Video={id:string;title:string;description?:string;thumbnail?:string;duration?:number;timestamp?:number;uploadDate?:string;uploader?:string;webpageUrl:string;maxHeight?:number;maxFps?:number;qualities:number[]};
type Settings={downloadDirectory:string;defaultQuality:string;maxConcurrentDownloads:number;saveThumbnail:boolean;language:Language};
type Progress={jobId:string;videoId:string;status:string;stage:string;percent?:number;downloadedBytes?:number;totalBytes?:number;speed?:number;eta?:number;message?:string;outputPath?:string;technicalDetails?:string};
type PersistedJob=Progress&{request:{item:Video;quality:string};settings:Settings;outputTemplate:string;createdAt:number;updatedAt:number;retryCount:number;maxRetries:number;nextRetryAt?:number};
type AppInfo={version:string;ytdlpVersion:string;ffmpegVersion:string};

const translations={
  en:{tagline:"Public videos, playlists, and archived streams",about:"About",url:"YouTube URL",load:"Load",loading:"Loading…",folder:"Download directory",choose:"Choose Folder",openFolder:"Open Folder",chooseTitle:"Choose download folder",thumbnail:"Save thumbnail as JPG",concurrency:"Concurrent downloads",selectAll:"Select All",clearSelection:"Clear Selection",items:(n:number)=>`${n} item${n===1?"":"s"}`,pasteBegin:"Paste a URL to begin",resumeAll:"Resume All",downloadSelected:"Download Selected",best:"Best Available",quality:"Quality",ready:"Ready",unknownChannel:"Unknown channel",unknownDate:"Date unknown",approx:"Approx.",retryIn:"Retry in",eta:"ETA",saved:"Saved to",technical:"Technical details",pause:"Pause",cancel:"Cancel",remove:"Remove",removeConfirm:"Remove this entry from the list? Active downloading will stop, but downloaded media and partial files will not be deleted.",resume:"Resume",download:"Download",downloadAgain:"Download Again",pasteUrl:"Paste a YouTube URL first.",version:"Version",description:"A lightweight Windows utility for browsing and downloading public YouTube videos, playlists, and archived livestreams.",developer:"Developer",project:"YouTube Live Downloader Project",distribution:"Distribution",portable:"Self-contained portable Windows application",legal:"Download only content you own or have permission to save. The application does not bypass DRM or authentication.",close:"Close",language:"Language",status:{queued:"Queued",preparing:"Preparing",downloading:"Downloading",pausing:"Pausing",paused:"Paused",retrying:"Retrying",merging:"Merging",completed:"Completed",failed:"Failed",cancelled:"Cancelled",interrupted:"Interrupted — Resume available"}},
  tr:{tagline:"Herkese açık videolar, oynatma listeleri ve arşiv yayınları",about:"Hakkında",url:"YouTube adresi",load:"Yükle",loading:"Yükleniyor…",folder:"İndirme klasörü",choose:"Klasör Seç",openFolder:"Klasörü Aç",chooseTitle:"İndirme klasörünü seçin",thumbnail:"Küçük resmi JPG olarak kaydet",concurrency:"Eşzamanlı indirme",selectAll:"Tümünü Seç",clearSelection:"Seçimi Temizle",items:(n:number)=>`${n} öğe`,pasteBegin:"Başlamak için bir adres yapıştırın",resumeAll:"Tümünü Devam Ettir",downloadSelected:"Seçilenleri İndir",best:"En İyi Kalite",quality:"Kalite",ready:"Hazır",unknownChannel:"Bilinmeyen kanal",unknownDate:"Tarih bilinmiyor",approx:"Yaklaşık",retryIn:"Yeniden deneme",eta:"Kalan",saved:"Kaydedildi",technical:"Teknik ayrıntılar",pause:"Duraklat",cancel:"İptal",remove:"Kaldır",removeConfirm:"Bu kayıt listeden kaldırılsın mı? Aktif indirme durdurulur ancak indirilen medya ve kısmi dosyalar silinmez.",resume:"Devam Et",download:"İndir",downloadAgain:"Tekrar İndir",pasteUrl:"Önce bir YouTube adresi yapıştırın.",version:"Sürüm",description:"Herkese açık YouTube videolarını, oynatma listelerini ve arşivlenmiş canlı yayınları görüntülemek ve indirmek için hafif bir Windows uygulaması.",developer:"Geliştirici",project:"YouTube Live Downloader Projesi",distribution:"Dağıtım",portable:"Bağımsız portable Windows uygulaması",legal:"Yalnızca sahibi olduğunuz veya kaydetme izniniz bulunan içerikleri indirin. Uygulama DRM veya kimlik doğrulamasını aşmaz.",close:"Kapat",language:"Dil",status:{queued:"Kuyrukta",preparing:"Hazırlanıyor",downloading:"İndiriliyor",pausing:"Duraklatılıyor",paused:"Duraklatıldı",retrying:"Yeniden deneniyor",merging:"Birleştiriliyor",completed:"Tamamlandı",failed:"Başarısız",cancelled:"İptal edildi",interrupted:"Kesildi — devam edilebilir"}}
} as const;
type StatusKey=keyof typeof translations.en.status;

const state:{videos:Video[];selected:Set<string>;qualities:Map<string,string>;jobs:Map<string,Progress>;settings?:Settings;loading:boolean;about?:AppInfo;url:string}={videos:[],selected:new Set(),qualities:new Map(),jobs:new Map(),loading:false,url:""};
const app=document.querySelector<HTMLDivElement>("#app")!;
const esc=(v:string)=>v.replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]!));
const lang=():Language=>state.settings?.language||"en";
const t=()=>translations[lang()];
const duration=(s?:number)=>{if(s==null)return"—";const h=Math.floor(s/3600),m=Math.floor(s%3600/60),x=Math.floor(s%60);return h?`${h}:${String(m).padStart(2,"0")}:${String(x).padStart(2,"0")}`:`${m}:${String(x).padStart(2,"0")}`};
const bytes=(n?:number)=>{if(n==null)return"—";let i=0;const u=["B","KB","MB","GB","TB"];while(n>=1024&&i<u.length-1){n/=1024;i++}return`${n.toFixed(i>1?1:0)} ${u[i]}`};
const date=(v:Video)=>v.timestamp?new Date(v.timestamp*1000).toLocaleDateString(lang()==="tr"?"tr-TR":"en-US"):v.uploadDate?.length===8?`${v.uploadDate.slice(0,4)}-${v.uploadDate.slice(4,6)}-${v.uploadDate.slice(6)}`:t().unknownDate;
const latest=(id:string)=>[...state.jobs.values()].filter(j=>j.videoId===id).at(-1);
const stage=(p?:Progress)=>{if(!p)return t().ready;const base=t().status[p.status as StatusKey];if(p.status==="retrying"){const attempt=p.stage.match(/attempt\s+(\d+\/\d+)/i)?.[1];return attempt?`${base} — ${attempt}`:base}return base||p.stage};
const qualityOptions=(v:Video)=>{const levels=[2160,1440,1080,720,480],available=v.qualities.length?levels.filter(q=>v.qualities.some(h=>h>=q)):levels;return[`<option value="best">${t().best}</option>`,...available.map(q=>`<option value="${q}p">${q}p</option>`)].join("")};

function render(){
  const s=state.settings,recoverable=[...state.jobs.values()].filter(j=>["paused","interrupted"].includes(j.status)).length;
  document.documentElement.lang=lang();
  app.innerHTML=`<header><div class="brand"><span class="mark">▶</span><div><h1>YouTube Live Downloader</h1><p>${t().tagline}</p></div></div><div class="header-actions"><label class="language"><span>${t().language}</span><select id="language"><option value="tr" ${lang()==="tr"?"selected":""}>Türkçe</option><option value="en" ${lang()==="en"?"selected":""}>English</option></select></label><button class="developer-link" data-developer-link>SERDARHOCAM</button><button id="about" class="ghost">${t().about}</button></div></header><main>
  <section class="controls panel"><label class="wide"><span>${t().url}</span><div class="row"><input id="url" type="url" value="${esc(state.url)}" placeholder="https://www.youtube.com/watch?v=…" autocomplete="off"><button id="load" class="primary" ${state.loading?"disabled":""}>${state.loading?'<i class="spinner"></i> '+t().loading:t().load}</button></div></label><label class="wide"><span>${t().folder}</span><div class="row"><input id="folder" value="${esc(s?.downloadDirectory||"")}" readonly><button id="open-folder">${t().openFolder}</button><button id="choose">${t().choose}</button></div></label><div class="setting-row"><label><input id="thumbs" type="checkbox" ${s?.saveThumbnail?"checked":""}> ${t().thumbnail}</label><label>${t().concurrency} <select id="concurrency">${[1,2,3,4].map(n=>`<option ${s?.maxConcurrentDownloads===n?"selected":""}>${n}</option>`).join("")}</select></label></div></section><div id="error"></div>
  <section class="list-head"><div><button id="select-all" class="ghost" ${!state.videos.length?"disabled":""}>${state.selected.size===state.videos.length&&state.videos.length?t().clearSelection:t().selectAll}</button><span>${state.videos.length?t().items(state.videos.length):t().pasteBegin}</span></div><div class="head-actions"><button id="resume-all" ${!recoverable?"disabled":""}>${t().resumeAll} (${recoverable})</button><button id="download-selected" class="primary" ${!state.selected.size?"disabled":""}>${t().downloadSelected} (${state.selected.size})</button></div></section><section class="videos">${state.loading?Array(2).fill('<article class="card skeleton"><div></div><section><b></b><p></p><p></p></section></article>').join(""):state.videos.map(card).join("")}</section></main>${state.about?aboutDialog(state.about):""}`;
  bind();
}

function aboutDialog(info:AppInfo){return`<div class="modal-backdrop" role="presentation"><section class="about-modal" role="dialog" aria-modal="true" aria-labelledby="about-title"><div class="about-heading"><span class="mark">▶</span><div><h2 id="about-title">YouTube Live Downloader</h2><p>${t().version} ${esc(info.version)}</p></div></div><p>${t().description}</p><dl><dt>${t().developer}</dt><dd><button class="about-developer" data-developer-link>SERDARHOCAM</button><span> — ${t().project}</span></dd><dt>yt-dlp</dt><dd>${esc(info.ytdlpVersion)}</dd><dt>FFmpeg</dt><dd>${esc(info.ffmpegVersion)}</dd><dt>${t().distribution}</dt><dd>${t().portable}</dd></dl><p class="legal">${t().legal}</p><button id="about-close" class="primary">${t().close}</button></section></div>`}

function card(v:Video){const p=latest(v.id),pct=Math.max(0,Math.min(100,p?.percent||0)),active=!!p&&["queued","preparing","downloading","pausing","retrying","merging"].includes(p.status),resumable=!!p&&["paused","interrupted","cancelled","failed"].includes(p.status),historical=!!p&&["paused","interrupted","cancelled"].includes(p.status),failed=p?.status==="failed";return`<article class="card" data-id="${esc(v.id)}"><label class="check"><input class="select" type="checkbox" ${state.selected.has(v.id)?"checked":""}></label><img src="${esc(v.thumbnail||"")}" alt="" loading="lazy"><section class="details"><div class="title-line"><h2>${esc(v.title)}</h2><span class="status ${p?.status||"ready"}">${esc(stage(p))}</span></div><p class="meta">${esc(v.uploader||t().unknownChannel)} <b>•</b> ${date(v)} <b>•</b> ${duration(v.duration)} ${v.maxHeight?`<b>•</b> ${v.maxHeight}p${(v.maxFps||0)>=50?Math.round(v.maxFps!):""}`:""}</p>${v.description?`<details><summary>${esc(v.description.slice(0,180))}${v.description.length>180?"…":""}</summary><p>${esc(v.description)}</p></details>`:""}${p?`<div class="progress"><div><span style="width:${pct}%"></span></div><p>${historical?t().approx+" ":""}${p.percent!=null?`${p.percent.toFixed(1)}% · `:""}${bytes(p.downloadedBytes)}${p.totalBytes?` / ${bytes(p.totalBytes)}`:""}${p.speed?` · ${bytes(p.speed)}/s`:""}${p.eta!=null?` · ${p.status==="retrying"?t().retryIn:t().eta} ${duration(p.eta)}`:""}</p>${p.message?`<p class="job-message">${esc(p.message)}</p>`:""}${p.outputPath?`<p class="path">${t().saved}: ${esc(p.outputPath)}</p>`:""}${(failed||p.status==="interrupted")&&p.technicalDetails?`<details class="error-detail"><summary>${t().technical}</summary><pre>${esc(p.technicalDetails)}</pre></details>`:""}</div>`:""}<div class="actions"><select class="quality" aria-label="${t().quality}" ${p&&!/completed|failed|cancelled/.test(p.status)?"disabled":""}>${qualityOptions(v)}</select>${active?`<button class="pause" data-job="${p!.jobId}" ${p!.status==="pausing"?"disabled":""}>${t().pause}</button><button class="cancel danger" data-job="${p!.jobId}">${t().cancel}</button>`:resumable?`<button class="resume primary" data-job="${p!.jobId}">${t().resume}</button>`:`<button class="download primary">${p?.status==="completed"?t().downloadAgain:t().download}</button>`}${p?`<button class="remove ghost" data-job="${p.jobId}">${t().remove}</button>`:""}</div></section></article>`}

function showError(e:unknown){const raw=String(e),[friendly,...rest]=raw.split("\n\nTechnical details:\n"),el=document.querySelector("#error");if(el)el.innerHTML=`<div class="error"><b>${esc(friendly)}</b>${rest.length?`<details><summary>${t().technical}</summary><pre>${esc(rest.join("\n"))}</pre></details>`:""}</div>`}
async function saveSettings(){if(state.settings)await invoke("save_settings",{settings:state.settings})}
async function loadUrl(){const input=document.querySelector<HTMLInputElement>("#url")!;state.url=input.value.trim();if(!state.url)return showError(t().pasteUrl);state.loading=true;render();try{state.videos=await invoke("load_metadata",{url:state.url});state.selected.clear();state.qualities.clear();await refreshJobs()}catch(e){showError(e)}finally{state.loading=false;render()}}
async function refreshJobs(){const jobs=await invoke<PersistedJob[]>("list_download_jobs");for(const job of jobs){state.jobs.set(job.jobId,{...job,videoId:job.request.item.id});if(!state.videos.some(v=>v.id===job.request.item.id))state.videos.push(job.request.item);state.qualities.set(job.request.item.id,job.request.quality)}}
async function queue(videos:Video[]){try{await invoke("queue_downloads",{requests:videos.map(item=>({item,quality:state.qualities.get(item.id)||"best"}))});await refreshJobs();render()}catch(e){showError(e)}}
async function removeJob(jobId:string,videoId:string){if(!confirm(t().removeConfirm))return;try{await invoke("remove_download_job",{jobId});state.jobs.delete(jobId);if(![...state.jobs.values()].some(job=>job.videoId===videoId)){state.videos=state.videos.filter(v=>v.id!==videoId);state.selected.delete(videoId);state.qualities.delete(videoId)}render()}catch(e){showError(e)}}

function bind(){
  document.querySelector("#load")?.addEventListener("click",loadUrl);
  document.querySelector("#url")?.addEventListener("input",e=>state.url=(e.target as HTMLInputElement).value);
  document.querySelector("#url")?.addEventListener("keydown",e=>{if((e as KeyboardEvent).key==="Enter")loadUrl()});
  document.querySelector("#language")?.addEventListener("change",async e=>{if(state.settings){state.settings.language=(e.target as HTMLSelectElement).value as Language;await saveSettings();render()}});
  document.querySelectorAll<HTMLElement>("[data-developer-link]").forEach(link=>link.addEventListener("click",()=>invoke("open_developer_website").catch(showError)));
  document.querySelector("#open-folder")?.addEventListener("click",()=>invoke("open_download_folder").catch(showError));
  document.querySelector("#choose")?.addEventListener("click",async()=>{const dir=await open({directory:true,multiple:false,title:t().chooseTitle,defaultPath:state.settings?.downloadDirectory});if(typeof dir==="string"&&state.settings){state.settings.downloadDirectory=dir;await saveSettings();render()}});
  document.querySelector("#thumbs")?.addEventListener("change",async e=>{if(state.settings){state.settings.saveThumbnail=(e.target as HTMLInputElement).checked;await saveSettings()}});
  document.querySelector("#concurrency")?.addEventListener("change",async e=>{if(state.settings){state.settings.maxConcurrentDownloads=Number((e.target as HTMLSelectElement).value);await saveSettings()}});
  document.querySelector("#select-all")?.addEventListener("click",()=>{if(state.selected.size===state.videos.length)state.selected.clear();else state.videos.forEach(v=>state.selected.add(v.id));render()});
  document.querySelector("#download-selected")?.addEventListener("click",()=>queue(state.videos.filter(v=>state.selected.has(v.id))));
  document.querySelector("#resume-all")?.addEventListener("click",()=>invoke("resume_all_downloads").then(refreshJobs).then(render).catch(showError));
  document.querySelectorAll<HTMLElement>(".card").forEach(el=>{const id=el.dataset.id!,v=state.videos.find(x=>x.id===id)!;el.querySelector(".select")?.addEventListener("change",e=>{(e.target as HTMLInputElement).checked?state.selected.add(id):state.selected.delete(id);render()});el.querySelector<HTMLSelectElement>(".quality")?.addEventListener("change",e=>state.qualities.set(id,(e.target as HTMLSelectElement).value));el.querySelector(".download")?.addEventListener("click",()=>queue([v]));for(const [selector,command]of[[".pause","pause_download"],[".resume","resume_download"],[".cancel","cancel_download"]]as const)el.querySelector(selector)?.addEventListener("click",e=>invoke(command,{jobId:(e.currentTarget as HTMLElement).getAttribute("data-job")}).catch(showError))});
  document.querySelectorAll<HTMLElement>(".remove").forEach(button=>button.addEventListener("click",()=>removeJob(button.dataset.job!,button.closest<HTMLElement>(".card")!.dataset.id!)));
  document.querySelector("#about")?.addEventListener("click",async()=>{try{state.about=await invoke<AppInfo>("get_app_info");render()}catch(e){showError(e)}});
  document.querySelector("#about-close")?.addEventListener("click",()=>{state.about=undefined;render()});
  document.querySelector(".modal-backdrop")?.addEventListener("click",e=>{if(e.target===e.currentTarget){state.about=undefined;render()}});
}

async function init(){state.settings=await invoke("get_settings");await listen<Progress>("download-progress",e=>{state.jobs.set(e.payload.jobId,e.payload);render()});await refreshJobs();render()}
init().catch(showError);
